--Q1. what is the total revenue generated by male vs female customers?



SELECT "Gender",
   SUM("Purchase_Amount")
FROM customer
WHERE 
   "Gender" = 'Male'
GROUP BY
   "Gender"


SELECT 
    "Gender", 
    SUM("Purchase_Amount")
FROM customer
GROUP BY "Gender";



--Q2. which customer used a discount but still spent more than the average amount??--

SELECT *
FROM customer
WHERE 
   "Discount_Applied" = 'Yes' AND
   "Purchase_Amount" > (SELECT AVG("Purchase_Amount") FROM customer)



--Q3. which are the top 5 products with the highest average review rating--

select "Item_Purchased",
        AVG("Review_Rating") as average_review
from customer

GROUP BY "Item_Purchased"
order by average_review DESC
limit 5

--Q4. compare the average purchase amounts between standard and express shipping--
select 
       AVG("Purchase_Amount"),
	   "Shipping_Type"
from customer
WHERE 
   "Shipping_Type" = 'Express' OR
   "Shipping_Type" = 'Standard' 
GROUP BY 
           "Shipping_Type"
       

--Q5. Do subscribed customers spend more ? compare average spend and total revenue between subscribers and non subscribers

select 
     "Subscription_Status",
     AVG("Purchase_Amount"),
	 SUM("Purchase_Amount")
from customer
where
   "Subscription_Status" = 'Yes' or
   "Subscription_Status" = 'No'
GROUP BY "Subscription_Status"


--Q1. what is the total revenue generated by male vs female customers?

select 
    "Gender",
	sum("Purchase_Amount")
from customer
group by 
   "Gender"

--Q2. which customer used a discount but still spent more than the average amount??--
select "Customer_ID",
       "Discount_Applied",
	   "Purchase_Amount"
from customer
where 
      "Discount_Applied" = 'Yes' AND 
      "Purchase_Amount" > (select AVG("Purchase_Amount") from customer)





--Q6.which 5 products have the highest percentage of purchases with discounts applied??--

SELECT 
    "Item_Purchased",
    ROUND((SUM(CASE WHEN "Discount_Applied" = 'Yes' THEN 1 ELSE 0 END) * 100.0) / COUNT("Item_Purchased"), 2) AS percent_discounted
FROM customer
GROUP BY 
    "Item_Purchased"
ORDER BY 
    percent_discounted DESC
LIMIT 5;







